sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ppreis/multi-docker-react-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ppreis/multi-docker-react-client-test npm run test

after_sucess:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker build -t ppreis/multi-docker-react-client ./client
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker build -t ppreis/multi-docker-react-api ./api
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker build -t ppreis/multi-docker-react-worker ./worker
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker build -t ppreis/multi-docker-react-nginx ./nginx
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker push ppreis/multi-docker-react-client
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker push ppreis/multi-docker-react-api
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker push ppreis/multi-docker-react-worker
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && docker push ppreis/multi-docker-react-nginx
  

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker-react-project'
  env: 'Multidockerreactproject-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-393726823884'
  bucket_path: 'multi-docker-react-project'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY