sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ppreis/multi-docker-react-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ppreis/multi-docker-react-client-test npm run test

after_sucess:
  - docker build -t ppreis/multi-docker-react-client ./client
  - docker build -t ppreis/multi-docker-react-api ./api
  - docker build -t ppreis/multi-docker-react-worker ./worker
  - docker build -t ppreis/multi-docker-react-nginx ./nginx
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push ppreis/multi-docker-react-client
  - docker push ppreis/multi-docker-react-api
  - docker push ppreis/multi-docker-react-worker
  - docker push ppreis/multi-docker-react-nginx
