sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ppreis/multi-docker-react-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ppreis/multi-docker-react-client-test npm run test

after_sucess:
  - docker build -t ppreis/multi-docker-react-client ./client
    if: branch = master
  - docker build -t ppreis/multi-docker-react-api ./api
    if: branch = master
  - docker build -t ppreis/multi-docker-react-worker ./worker
    if: branch = master
  - docker build -t ppreis/multi-docker-react-nginx ./nginx
    if: branch = master
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    if: branch = master
  - docker push ppreis/multi-docker-react-client
    if: branch = master
  - docker push ppreis/multi-docker-react-api
    if: branch = master
  - docker push ppreis/multi-docker-react-worker
    if: branch = master
  - docker push ppreis/multi-docker-react-nginx
    if: branch = master
  

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker-react-project'
  env: 'Multidockerreactproject-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-393726823884'
  bucket_path: 'multi-docker-react-project'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY