apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
    containers:
      - name: client
        image: ppreis/multi-docker-react-client-k8s
        ports:
          - containerPort: 3000
